restaurant/items/urls.py
from .views import *
from django.urls import path

app_name = 'items'

urlpatterns = [
    path('menu/', menu, name='menu'),
    path('category/<slug:category_slug>/', menu, name='menu_by_category'),
    path('add/<int:item_id>/', menu, name='menu_add_to_order'),
    path('item/<int:id>/<slug:slug>/', item_detail, name='item_detail'),

]

restaurant/orders/urls.py
from . import views
from django.urls import path

app_name = 'orders'

urlpatterns = [
    path('add/<int:item_id>/', views.order_add, name='order_add'),
    path('', views.order_detail, name='order_detail'),
    path('remove/<int:item_id>/', views.order_item_remove, name='order_item_remove'),
    path('subtract/<int:item_id>/', views.order_subtract, name='order_subtract'),
    path('clear/', views.order_clear, name='order_clear'),
    path('create/', views.order_create, name='order_create'),
    path('receipt/', views.order_receipt_view, name='order_receipt'),
]

restaurant/restaurant/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('settings/', views.settings, name='settings'),
    path('orders/', include('orders.urls'), name='orders'),
    path('items/', include('items.urls'), name='items'),
    path('employees/', include('employees.urls'), name='employees'),
]

restaurant/orders/models.py
from django.db import models
from items.models import Item
from employees.models import Employee

# Create your models here.
class Order(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    cashier = models.ForeignKey(Employee, related_name='orders', on_delete=models.CASCADE, default=1)
    receipt = models.ImageField(upload_to='receipts/', blank=True, null=True)


    def __str__(self):
        return str(self.id)
    

    def get_total_price(self):
        return sum(item.get_total_price() for item in self.items.all())
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    item = models.ForeignKey(Item, related_name="order_items", on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)


    def get_total_price(self):
        return self.item.price * self.quantity

restaurant/orders/forms.py
from django import forms
from .models import Order, OrderItem

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['cashier', 'order_date', 'order_items', 'total_amount']

class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['order', 'item', 'quantity']

restaurant/orders/views.py
from django.shortcuts import render, get_object_or_404
from .models import Order, OrderItem
from items.models import Item
from employees.models import Employee
from django.views.decorators.http import require_POST
from django.http import JsonResponse
import json
from datetime import datetime
import io
#from .print_receipt import printReceipt

# Create your views here.
@require_POST
def order_create(request):
    payment_values = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
    user = get_object_or_404(Employee, id=request.user.id)
    order = Order.objects.create(cashier=user)
    order_data = request.POST.get('order_data')
    order_data = json.loads(order_data)
    for order_item in order_data:
        item = get_object_or_404(Item, id=order_item['item_id'])
        OrderItem.objects.create(order=order, item=item, quantity=order_item['item_quantity'])
    order.save()
    order_items = OrderItem.objects.filter(order=order)
    total_price = sum(item.get_total_price() for item in order_items)
    
    return render(request, 'orders/order_detail.html', {'order': order, 'order_items': order_items, 'total_price': total_price, 'payment_values': payment_values})

@require_POST
def order_add(request, item_id):
    order_id = request.session.get('order_id')

    if order_id:
        try:
            order = Order.objects.get(id=order_id)
        except Order.DoesNotExist:
            order = Order.objects.create()
    else:
        order = Order.objects.create()
        request.session['order_id'] = order.id

    item = get_object_or_404(Item, id=item_id)

    order_item, created = OrderItem.objects.get_or_create(order=order, item=item)
    if not created:
        order_item.quantity += 1

    order_item.save()

    response_data = {
        "success": True,
        "message": f"{item.name} added to order",
    }

    return JsonResponse(response_data)

@require_POST
def order_subtract(request, item_id):
    order_id = request.session.get('order_id')

    order = get_object_or_404(Order, id=order_id)
    item = get_object_or_404(OrderItem, id=item_id, order=order)

    if item.quantity > 1:
        item.quantity -= 1
        item.save()
    else:
        item.delete()

    response_data = {
        "success": True,
        "message": f"{{item.name}} removed from order",
    }

    return JsonResponse(response_data)

@require_POST
def order_clear(request):
    order_id = request.session.get('order_id')

    if order_id:
        try:
            order = Order.objects.get(id=order_id)
        except Order.DoesNotExist:
            order = Order.objects.create()
    else:
        order = Order.objects.create()
        request.session['order_id'] = order.id

    order_items = OrderItem.objects.filter(order=order)
    order_items.delete()

    response_data = {
        "success": True,
        "message": "Order cleared",
    }

    return JsonResponse(response_data)

@require_POST
def order_item_remove(request, item_id):
    order_id = request.session.get('order_id')

    order = get_object_or_404(Order, id=order_id)
    item = get_object_or_404(OrderItem, id=item_id, order=order)

    item.delete()

    response_data = {
        "success": True,
        "message": f"{{item.name}} removed from order",
    }

    return JsonResponse(response_data)

def order_detail(request):
    order_id = request.session.get('order_id')
    order=None
    
    if order_id:
        order = get_object_or_404(Order, id=order_id)
    if not order or not order.items.exists():
        order = None
    
    return render(request, 'orders/order_detail.html', {'order': order})

@require_POST
def order_receipt_view(request):

    order_id = request.POST.get('order_id')
    payment_amount = float(request.POST.get('payment_amount'))
    order = get_object_or_404(Order, id=order_id)
    order_items = OrderItem.objects.filter(order=order)
    date = order.created_at.strftime('%Y-%m-%d %H:%M:%S')
    #printReceipt(order_id, order_items, date)
    receipt = Receipt(order, payment_amount)
    kitchen_order = KitchenOrder(order)
    return render(request, 'orders/receipt.html', {'receipt': receipt, 'kitchen_order': kitchen_order})
    

    

class Receipt:
    def __init__(self, order, payment_amount):
        self.order_id = order.id
        self.items_list = OrderItem.objects.filter(order=order)
        self.order_items = [
            {
                'item_name': item.item.name,
                'item_quantity': item.quantity,
                'item_price': item.item.price,
                'item_total_price': item.quantity * item.item.price
            }
            for item in self.items_list
        ]
        self.order_total_price = sum(item['item_total_price'] for item in self.order_items)
        self.cashier = order.cashier
        self.payment_amount = payment_amount
        self.change = self.payment_amount - float(self.order_total_price)
        self.datetime = datetime.now()

    def __str__(self):
        receipt_lines = [
            f"Pizza Shop: +218-94-6446559",
            f"Order #: {self.order_id}",
            f"Cashier: {self.cashier}",
            f"Time: {self.datetime.strftime('%Y-%m-%d %H:%M:%S')}",
            f"--------------------------------"
        ]
        for item in self.order_items:
            receipt_lines.append(
                f"  - {item['item_name']} x {item['item_quantity']} @ {item['item_price']} each: {item['item_total_price']}"
            )
        receipt_lines.append(f"Total: {self.order_total_price}")
        receipt_lines.append(f"Payment Amount: {self.payment_amount}")
        receipt_lines.append(f"Change: {self.change}")
        return "\n".join(receipt_lines)
    
class KitchenOrder:
    def __init__(self, order):
        self.order_id = order.id
        self.items_list = OrderItem.objects.filter(order=order)
        self.order_items = [
            {
                'item_name': item.item.name,
                'item_quantity': item.quantity
            }
            for item in self.items_list
        ]
        self.datetime = datetime.now()

    def __str__(self):
        order_lines = [
            f"ORDER NUMBER: {self.order_id}",
            f"Time: {self.datetime.strftime('%Y-%m-%d %H:%M:%S')}",
            f"--------------------------------"
        ]
        for item in self.order_items:
            order_lines.append(
                f"  - {item['item_name']} x {item['item_quantity']}"
            )
        return "\n".join(order_lines)
    

restaurant/orders/templates/orders/order_detail.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}Order #{{ order.id }}{% endblock %}

{% block content %}
<div class="container-fluid p-3 text-light bg-secondary rounded">
    <div class="row">
        <div class="col col-8">
            <h2>
                ORDER #{{ order.id }}:
            </h2>
            <table class="table table-borderless text-light rounded">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in order_items %}
                    <tr>
                        <td>{{ item.item.name }}</td>
                        <td>${{ item.item.price }}</td>
                        <td>x {{ item.quantity }}</td>
                        <td>${{ item.get_total_price }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col col-3 p-4">
            <div class="row px-2">
                {% for value in payment_values %}
                <button type="button" class="shadow-lg btn btn-dark btn-lg col col-4 m-1" value="{{ value }}" onclick="addToPayment(event)">&dollar; {{ value }}</button>
                {% endfor %}
                <button type="button" class="shadow-lg btn btn-dark btn-lg col col-8 m-1" value="{{ total_price }}" onclick="addToPayment(event)">&dollar; {{ total_price }}</button>
            </div>
            <div class="p-1 my-3">
                <form id="payment-form" action="{% url 'orders:order_receipt' %}" method="post" onsubmit="return validatePayment()">
                    {% csrf_token %}
                    <input type="hidden" name="order_id" value="{{ order.id }}">
                    <input id="payment-amount" name="payment_amount" type="number" placeholder="0.00" step="0.25" class="w-50 rounded p-2" value="0"/>
                    <button type="submit" class="shadow-lg btn btn-primary btn-lg col col-6 my-1">Pay</button>
                </form>
                <div id="payment-warning" class="text-danger" style="display: none;">Payment amount is insufficient!</div>
            </div>
        </div>
    </div>
    <div>
        <h3>Total: ${{ total_price }}</h3>
    </div>
</div>

<script>
    function addToPayment(event) {
        let paymentAmount = document.getElementById('payment-amount');
        paymentAmount.value = parseFloat(paymentAmount.value) + parseFloat(event.target.value);
    }

    function validatePayment() {
        let paymentAmount = parseFloat(document.getElementById('payment-amount').value);
        let totalPrice = parseFloat("{{ total_price }}");

        if (paymentAmount < totalPrice) {
            document.getElementById('payment-warning').style.display = 'block';
            return false;
        } else {
            document.getElementById('payment-warning').style.display = 'none';
            return true;
        }
    }
</script>

{% endblock %}

restaurant/orders/templates/orders/receipt.html
{% extends 'layout.html' %}

{% load static %}

{% block title %}Order #{{ order.id }}{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div id="receipt" class="col bg-light m-1">
            <span style="white-space: pre-line">{{receipt}}</span>
        </div>
        <div id="kitchen-order" class="col bg-light m-1">
            <span style="white-space: pre-line">{{ kitchen_order }}</span>
        </div>
        
    </div>
    <a href="{% url 'items:menu' %}" class="btn btn-primary btn-lg m-3" role="button">Continue</a>
</div>
{% endblock %}